//
//  PresetColorPickerViewController.m
//  Created by http://github.com/iosdeveloper
//

#import "PresetColorPickerViewController.h"

@implementation PresetColorPickerViewController

- (void)viewDidLoad {
    [super viewDidLoad];
	
	UIButton *button = [UIButton buttonWithType:UIButtonTypeCustom];
	[button addTarget:self action:@selector(selectColor) forControlEvents:UIControlEventTouchUpInside];
	[button setFrame:CGRectMake(0.0, 0.0, 320.0, 460.0)];
	[button setAutoresizingMask:UIViewAutoresizingFlexibleHeight | UIViewAutoresizingFlexibleWidth];
	[button setTag:100];
	[button setTitle:@"Select color" forState:UIControlStateNormal];
	[button setTitleColor:[UIColor darkTextColor] forState:UIControlStateNormal];
	
	[[self view] addSubview:button];
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation {
    return YES;
}

- (void)selectColor {
	PresetColorPicker *colorPicker = [[PresetColorPicker alloc] init];
	[colorPicker setPresetColors:[NSArray arrayWithObjects:@"Black",
								  @"Dark Grey",
								  @"Light Grey",
								  @"Grey",
								  @"White",
								  @"Red",
								  @"Green",
								  @"Blue",
								  @"Cyan",
								  @"Yellow",
								  @"Magenta",
								  @"Orange",
								  @"Purple",
								  @"Brown",
								  @"Skyblue",
								  @"Lawngreen",
								  @"Chocolate",
								  @"aliceBlue",
								  @"alizarin",
								  @"amaranth",
								  @"amber",
								  @"amethyst",
								  @"apricot",
								  @"aqua",
								  @"aquamarine",
								  @"armyGreen",
								  @"asparagus",
								  @"atomicTangerine",
								  @"auburn",
								  @"azure",
								  @"azureWeb",
								  @"babyBlue",
								  @"beige",
								  @"bistre",
								  @"black",
								  @"blue",
								  @"pigmentBlue",
								  @"rybBlue",
								  @"blueGreen",
								  @"blueViolet",
								  @"bondiBlue",
								  @"brass",
								  @"brightGreen",
								  @"brightPink",
								  @"brightTurquoise",
								  @"brilliantRose",
								  @"britishRacingGreen",
								  @"bronze",
								  @"brown",
								  @"buff",
								  @"burgundy",
								  @"burntOrange",
								  @"burntSienna",
								  @"burntUmber",
								  @"camouflageGreen",
								  @"caputMortuum",
								  @"cardinal",
								  @"carmine",
								  @"carnationPink",
								  @"carolinaBlue",
								  @"carrotOrange",
								  @"celadon",
								  @"cerise",
								  @"cerulean",
								  @"ceruleanBlue",
								  @"champagne",
								  @"charcoal",
								  @"chartreuse",
								  @"chartreuseWeb",
								  @"cherryBlossomPink",
								  @"chestnut",
								  @"chocolate",
								  @"cinnabar",
								  @"cinnamon",
								  @"cobalt",
								  @"columbiaBlue",
								  @"copper",
								  @"copperRose",
								  @"coral",
								  @"coralRed",
								  @"corn",
								  @"cornflowerBlue",
								  @"cosmicLatte",
								  @"cream",
								  @"crimson",
								  @"cyan",
								  @"processCyan",
								  @"darkBlue",
								  @"darkBrown",
								  @"darkCerulean",
								  @"darkChestnut",
								  @"darkCoral",
								  @"darkGoldenrod",
								  @"darkGreen",
								  @"darkKhaki",
								  @"darkPastelGreen",
								  @"darkPink",
								  @"darkScarlet",
								  @"darkSalmon",
								  @"darkSlateGray",
								  @"darkSpringGreen",
								  @"darkTan",
								  @"darkTurquoise",
								  @"darkViolet",
								  @"deepCerise",
								  @"deepChestnut",
								  @"deepFuchsia",
								  @"deepLilac",
								  @"deepMagenta",
								  @"deepPeach",
								  @"deepPink",
								  @"denim",
								  @"dodgerBlue",
								  @"ecru",
								  @"egyptianBlue",
								  @"electricBlue",
								  @"electricGreen",
								  @"electricIndigo",
								  @"electricLime",
								  @"electricPurple",
								  @"emerald",
								  @"eggplant",
								  @"faluRed",
								  @"fernGreen",
								  @"firebrick",
								  @"flax",
								  @"forestGreen",
								  @"frenchRose",
								  @"fuchsia",
								  @"fuchsiaPink",
								  @"gamboge",
								  @"metallicGold",
								  @"goldWeb",
								  @"goldenBrown",
								  @"goldenYellow",
								  @"goldenrod",
								  @"greyAsparagus",
								  @"green",
								  @"greenWeb",
								  @"pigmentGreen",
								  @"rybGreen",
								  @"greenYellow",
								  @"grey",
								  @"hanPurple",
								  @"harlequin",
								  @"heliotrope",
								  @"hollywoodCerise",
								  @"hotMagenta",
								  @"hotPink",
								  @"indigo",
								  @"indigoWeb",
								  @"internationalKleinBlue",
								  @"internationalOrange",
								  @"islamicGreen",
								  @"ivory",
								  @"jade",
								  @"kellyGreen",
								  @"khaki",
								  @"lightKhaki",
								  @"lavender",
								  @"lavenderWeb",
								  @"lavenderBlue",
								  @"lavenderBlush",
								  @"lavenderGrey",
								  @"lavenderMagenta",
								  @"lavenderPink",
								  @"lavenderPurple",
								  @"lavenderRose",
								  @"lawnGreen",
								  @"lemon",
								  @"lemonChiffon",
								  @"lightBlue",
								  @"lightPink",
								  @"lilac",
								  @"lime",
								  @"limeWeb",
								  @"limeGreen",
								  @"linen",
								  @"magenta",
								  @"magentaDye",
								  @"processMagenta",
								  @"magicMint",
								  @"magnolia",
								  @"malachite",
								  @"maroonWeb",
								  @"maroon",
								  @"mayaBlue",
								  @"mauve",
								  @"mauveTaupe",
								  @"mediumBlue",
								  @"mediumCarmine",
								  @"mediumLavenderMagenta",
								  @"mediumPurple",
								  @"mediumSpringGreen",
								  @"midnightBlue",
								  @"mintGreen",
								  @"mistyRose",
								  @"mossGreen",
								  @"mountbattenPink",
								  @"mustard",
								  @"myrtle",
								  @"navajoWhite",
								  @"navyBlue",
								  @"ochre",
								  @"officeGreen",
								  @"oldGold",
								  @"oldLace",
								  @"oldLavender",
								  @"oldRose",
								  @"olive",
								  @"oliveDrab",
								  @"olivine",
								  @"orange",
								  @"rybOrange",
								  @"orangeWeb",
								  @"orangePeel",
								  @"orangeRed",
								  @"orchid",
								  @"paleBlue",
								  @"paleBrown",
								  @"paleCarmine",
								  @"paleChestnut",
								  @"paleCornflowerBlue",
								  @"paleMagenta",
								  @"palePink",
								  @"paleRedViolet",
								  @"papayaWhip",
								  @"pastelGreen",
								  @"pastelPink",
								  @"peach",
								  @"peachOrange",
								  @"peachYellow",
								  @"pear",
								  @"periwinkle",
								  @"persianBlue",
								  @"persianGreen",
								  @"persianIndigo",
								  @"persianOrange",
								  @"persianRed",
								  @"persianPink",
								  @"persianRose",
								  @"persimmon",
								  @"pineGreen",
								  @"pink",
								  @"pinkOrange",
								  @"platinum",
								  @"plum",
								  @"powderBlue",
								  @"puce",
								  @"prussianBlue",
								  @"psychedelicPurple",
								  @"pumpkin",
								  @"purpleWeb",
								  @"purple",
								  @"purpleTaupe",
								  @"rawUmber",
								  @"razzmatazz",
								  @"red",
								  @"pigmentRed",
								  @"rybRed",
								  @"redBiolet",
								  @"richCarmine",
								  @"robinEggBlue",
								  @"rose",
								  @"roseMadder",
								  @"roseTaupe",
								  @"royalBlue",
								  @"royalPurple",
								  @"ruby",
								  @"russet",
								  @"rust",
								  @"safetyOrange",
								  @"blazeOrange",
								  @"saffron",
								  @"salmon",
								  @"sandyBrown",
								  @"sangria",
								  @"sapphire",
								  @"scarlet",
								  @"schoolBusYellow",
								  @"seaGreen",
								  @"seashell",
								  @"selectiveYellow",
								  @"sepia",
								  @"shamrockGreen",
								  @"shockingPink",
								  @"silver",
								  @"skyBlue",
								  @"slateGrey",
								  @"smalt",
								  @"springBud",
								  @"springGreen",
								  @"steelBlue",
								  @"tan",
								  @"tangerine",
								  @"tangerineYellow",
								  @"taupe",
								  @"teaGreen",
								  @"teaRoseOrange",
								  @"teaRose",
								  @"teal",
								  @"tawny",
								  @"terraCotta",
								  @"thistle",
								  @"tomato",
								  @"turquoise",
								  @"tyrianPurple",
								  @"ultramarine",
								  @"unitedNationsBlue",
								  @"vegasGold",
								  @"vermilion",
								  @"violet",
								  @"violetWeb",
								  @"rybViolet",
								  @"viridian",
								  @"wheat",
								  @"white",
								  @"wisteria",
								  @"yellow",
								  @"processYellow",
								  @"rybYellow",
								  @"yellowGreen",
								  @"zinnwaldite",
								  [UIColor blackColor],
								  [UIColor darkGrayColor],
								  [UIColor lightGrayColor],
								  [UIColor grayColor],
								  [UIColor whiteColor],
								  [UIColor redColor],
								  [UIColor greenColor],
								  [UIColor blueColor],
								  [UIColor cyanColor],
								  [UIColor yellowColor],
								  [UIColor magentaColor],
								  [UIColor orangeColor],
								  [UIColor purpleColor],
								  [UIColor brownColor],
								  [UIColor colorWithRed:135.0 / 255.0 green:206.0 / 255.0 blue:235.0 / 255.0 alpha:1.0],
								  [UIColor colorWithHue:90.0 / 255.0 saturation:100.0 / 255.0 brightness:99.0 / 255.0 alpha:1.0],
								  [UIColor colorWithRed:210.0 / 255.0 green:105.0 / 255.0 blue:30.0 / 255.0 alpha:1.0],
                                    [UIColor aliceBlue],
                                    [UIColor alizarin],
                                    [UIColor amaranth],
                                    [UIColor amber],
                                    [UIColor amethyst],
                                    [UIColor apricot],
                                    [UIColor aqua],
                                    [UIColor aquamarine],
                                    [UIColor armyGreen],
                                    [UIColor asparagus],
                                    [UIColor atomicTangerine],
                                    [UIColor auburn],
                                    [UIColor azure],
                                    [UIColor azureWeb],
                                    [UIColor babyBlue],
                                    [UIColor beige],
                                    [UIColor bistre],
                                    [UIColor black],
                                    [UIColor blue],
                                    [UIColor pigmentBlue],
                                    [UIColor rybBlue],
                                    [UIColor blueGreen],
                                    [UIColor blueViolet],
                                    [UIColor bondiBlue],
                                    [UIColor brass],
                                    [UIColor brightGreen],
                                    [UIColor brightPink],
                                    [UIColor brightTurquoise],
                                    [UIColor brilliantRose],
                                    [UIColor britishRacingGreen],
                                    [UIColor bronze],
                                    [UIColor brown],
                                    [UIColor buff],
                                    [UIColor burgundy],
                                    [UIColor burntOrange],
                                    [UIColor burntSienna],
                                    [UIColor burntUmber],
                                    [UIColor camouflageGreen],
                                    [UIColor caputMortuum],
                                    [UIColor cardinal],
                                    [UIColor carmine],
                                    [UIColor carnationPink],
                                    [UIColor carolinaBlue],
                                    [UIColor carrotOrange],
                                    [UIColor celadon],
                                    [UIColor cerise],
                                    [UIColor cerulean],
                                    [UIColor ceruleanBlue],
                                    [UIColor champagne],
                                    [UIColor charcoal],
                                    [UIColor chartreuse],
                                    [UIColor chartreuseWeb],
                                    [UIColor cherryBlossomPink],
                                    [UIColor chestnut],
                                    [UIColor chocolate],
                                    [UIColor cinnabar],
                                    [UIColor cinnamon],
                                    [UIColor cobalt],
                                    [UIColor columbiaBlue],
                                    [UIColor copper],
                                    [UIColor copperRose],
                                    [UIColor coral],
                                    [UIColor coralRed],
                                    [UIColor corn],
                                    [UIColor cornflowerBlue],
                                    [UIColor cosmicLatte],
                                    [UIColor cream],
                                    [UIColor crimson],
                                    [UIColor cyan],
                                    [UIColor processCyan],
                                    [UIColor darkBlue],
                                    [UIColor darkBrown],
                                    [UIColor darkCerulean],
                                    [UIColor darkChestnut],
                                    [UIColor darkCoral],
                                    [UIColor darkGoldenrod],
                                    [UIColor darkGreen],
                                    [UIColor darkKhaki],
                                    [UIColor darkPastelGreen],
                                    [UIColor darkPink],
                                    [UIColor darkScarlet],
                                    [UIColor darkSalmon],
                                    [UIColor darkSlateGray],
                                    [UIColor darkSpringGreen],
                                    [UIColor darkTan],
                                    [UIColor darkTurquoise],
                                    [UIColor darkViolet],
                                    [UIColor deepCerise],
                                    [UIColor deepChestnut],
                                    [UIColor deepFuchsia],
                                    [UIColor deepLilac],
                                    [UIColor deepMagenta],
                                    [UIColor deepPeach],
                                    [UIColor deepPink],
                                    [UIColor denim],
                                    [UIColor dodgerBlue],
                                    [UIColor ecru],
                                    [UIColor egyptianBlue],
                                    [UIColor electricBlue],
                                    [UIColor electricGreen],
                                    [UIColor electricIndigo],
                                    [UIColor electricLime],
                                    [UIColor electricPurple],
                                    [UIColor emerald],
                                    [UIColor eggplant],
                                    [UIColor faluRed],
                                    [UIColor fernGreen],
                                    [UIColor firebrick],
                                    [UIColor flax],
                                    [UIColor forestGreen],
                                    [UIColor frenchRose],
                                    [UIColor fuchsia],
                                    [UIColor fuchsiaPink],
                                    [UIColor gamboge],
                                    [UIColor metallicGold],
                                    [UIColor goldWeb],
                                    [UIColor goldenBrown],
                                    [UIColor goldenYellow],
                                    [UIColor goldenrod],
                                    [UIColor greyAsparagus],
                                    [UIColor green],
                                    [UIColor greenWeb],
                                    [UIColor pigmentGreen],
                                    [UIColor rybGreen],
                                    [UIColor greenYellow],
                                    [UIColor grey],
                                    [UIColor hanPurple],
                                    [UIColor harlequin],
                                    [UIColor heliotrope],
                                    [UIColor hollywoodCerise],
                                    [UIColor hotMagenta],
                                    [UIColor hotPink],
                                    [UIColor indigo],
                                    [UIColor indigoWeb],
                                    [UIColor internationalKleinBlue],
                                    [UIColor internationalOrange],
                                    [UIColor islamicGreen],
                                    [UIColor ivory],
                                    [UIColor jade],
                                    [UIColor kellyGreen],
                                    [UIColor khaki],
                                    [UIColor lightKhaki],
                                    [UIColor lavender],
                                    [UIColor lavenderWeb],
                                    [UIColor lavenderBlue],
                                    [UIColor lavenderBlush],
                                    [UIColor lavenderGrey],
                                    [UIColor lavenderMagenta],
                                    [UIColor lavenderPink],
                                    [UIColor lavenderPurple],
                                    [UIColor lavenderRose],
                                    [UIColor lawnGreen],
                                    [UIColor lemon],
                                    [UIColor lemonChiffon],
                                    [UIColor lightBlue],
                                    [UIColor lightPink],
                                    [UIColor lilac],
                                    [UIColor lime],
                                    [UIColor limeWeb],
                                    [UIColor limeGreen],
                                    [UIColor linen],
                                    [UIColor magenta],
                                    [UIColor magentaDye],
                                    [UIColor processMagenta],
                                    [UIColor magicMint],
                                    [UIColor magnolia],
                                    [UIColor malachite],
                                    [UIColor maroonWeb],
                                    [UIColor maroon],
                                    [UIColor mayaBlue],
                                    [UIColor mauve],
                                    [UIColor mauveTaupe],
                                    [UIColor mediumBlue],
                                    [UIColor mediumCarmine],
                                    [UIColor mediumLavenderMagenta],
                                    [UIColor mediumPurple],
                                    [UIColor mediumSpringGreen],
                                    [UIColor midnightBlue],
                                    [UIColor mintGreen],
                                    [UIColor mistyRose],
                                    [UIColor mossGreen],
                                    [UIColor mountbattenPink],
                                    [UIColor mustard],
                                    [UIColor myrtle],
                                    [UIColor navajoWhite],
                                    [UIColor navyBlue],
                                    [UIColor ochre],
                                    [UIColor officeGreen],
                                    [UIColor oldGold],
                                    [UIColor oldLace],
                                    [UIColor oldLavender],
                                    [UIColor oldRose],
                                    [UIColor olive],
                                    [UIColor oliveDrab],
                                    [UIColor olivine],
                                    [UIColor orange],
                                    [UIColor rybOrange],
                                    [UIColor orangeWeb],
                                    [UIColor orangePeel],
                                    [UIColor orangeRed],
                                    [UIColor orchid],
                                    [UIColor paleBlue],
                                    [UIColor paleBrown],
                                    [UIColor paleCarmine],
                                    [UIColor paleChestnut],
                                    [UIColor paleCornflowerBlue],
                                    [UIColor paleMagenta],
                                    [UIColor palePink],
                                    [UIColor paleRedViolet],
                                    [UIColor papayaWhip],
                                    [UIColor pastelGreen],
                                    [UIColor pastelPink],
                                    [UIColor peach],
                                    [UIColor peachOrange],
                                    [UIColor peachYellow],
                                    [UIColor pear],
                                    [UIColor periwinkle],
                                    [UIColor persianBlue],
                                    [UIColor persianGreen],
                                    [UIColor persianIndigo],
                                    [UIColor persianOrange],
                                    [UIColor persianRed],
                                    [UIColor persianPink],
                                    [UIColor persianRose],
                                    [UIColor persimmon],
                                    [UIColor pineGreen],
                                    [UIColor pink],
                                    [UIColor pinkOrange],
                                    [UIColor platinum],
                                    [UIColor plum],
                                    [UIColor powderBlue],
                                    [UIColor puce],
                                    [UIColor prussianBlue],
                                    [UIColor psychedelicPurple],
                                    [UIColor pumpkin],
                                    [UIColor purpleWeb],
                                    [UIColor purple],
                                    [UIColor purpleTaupe],
                                    [UIColor rawUmber],
                                    [UIColor razzmatazz],
                                    [UIColor red],
                                    [UIColor pigmentRed],
                                    [UIColor rybRed],
                                    [UIColor redBiolet],
                                    [UIColor richCarmine],
                                    [UIColor robinEggBlue],
                                    [UIColor rose],
                                    [UIColor roseMadder],
                                    [UIColor roseTaupe],
                                    [UIColor royalBlue],
                                    [UIColor royalPurple],
                                    [UIColor ruby],
                                    [UIColor russet],
                                    [UIColor rust],
                                    [UIColor safetyOrange],
                                    [UIColor blazeOrange],
                                    [UIColor saffron],
                                    [UIColor salmon],
                                    [UIColor sandyBrown],
                                    [UIColor sangria],
                                    [UIColor sapphire],
                                    [UIColor scarlet],
                                    [UIColor schoolBusYellow],
                                    [UIColor seaGreen],
                                    [UIColor seashell],
                                    [UIColor selectiveYellow],
                                    [UIColor sepia],
                                    [UIColor shamrockGreen],
                                    [UIColor shockingPink],
                                    [UIColor silver],
                                    [UIColor skyBlue],
                                    [UIColor slateGrey],
                                    [UIColor smalt],
                                    [UIColor springBud],
                                    [UIColor springGreen],
                                    [UIColor steelBlue],
                                    [UIColor tan],
                                    [UIColor tangerine],
                                    [UIColor tangerineYellow],
                                    [UIColor taupe],
                                    [UIColor teaGreen],
                                    [UIColor teaRoseOrange],
                                    [UIColor teaRose],
                                    [UIColor teal],
                                    [UIColor tawny],
                                    [UIColor terraCotta],
                                    [UIColor thistle],
                                    [UIColor tomato],
                                    [UIColor turquoise],
                                    [UIColor tyrianPurple],
                                    [UIColor ultramarine],
                                    [UIColor unitedNationsBlue],
                                    [UIColor vegasGold],
                                    [UIColor vermilion],
                                    [UIColor violet],
                                    [UIColor violetWeb],
                                    [UIColor rybViolet],
                                    [UIColor viridian],
                                    [UIColor wheat],
                                    [UIColor white],
                                    [UIColor wisteria],
                                    [UIColor yellow],
                                    [UIColor processYellow],
                                    [UIColor rybYellow],
                                    [UIColor yellowGreen],
                                    [UIColor zinnwaldite],
                                        nil]];
	[colorPicker setDelegate:self];
	
	[self presentModalViewController:colorPicker animated:YES];
	
	[colorPicker release];
}

- (void)colorSelected:(UIColor *)color {
	[(UIButton *)[[self view] viewWithTag:100] setBackgroundColor:color];
}

@end